apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - argocd-ingress.yaml
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml

patches:
  # Frontend
  - target:
      kind: Service
      name: frontend
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
