apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# 이미지 태그 변경을 위해 필요한 이미지들을 미리 등록해둡니다.
# CI/CD 파이프라인에서 'kustomize edit set image' 명령어로 이 부분의 newTag가 업데이트됩니다.
images:
  - name: coffee_machine/billing
    newName: coffee_machine/billing # 실제 ECR 주소는 CI/CD에서 주입되거나 여기서 고정 가능
  - name: coffee_machine/frontend
    newName: coffee_machine/frontend
  - name: coffee_machine/inventory
    newName: coffee_machine/inventory
  - name: coffee_machine/order
    newName: coffee_machine/order
