apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# 이미지 태그 변경을 위해 필요한 이미지들을 미리 등록해둡니다.
# CI/CD 파이프라인에서 'kustomize edit set image' 명령어로 이 부분의 newTag가 업데이트됩니다.
images:
- name: 637341921879.dkr.ecr.ap-northeast-2.amazonaws.com/coffee_machine
  newTag: frontend-41952d17c8e793b976b39727b1953c164e89e4ab
- name: coffee_machine/billing
  newName: coffee_machine/billing
- name: coffee_machine/frontend
  newName: 637341921879.dkr.ecr.ap-northeast-2.amazonaws.com/coffee_machine
  newTag: frontend-5618b411dd5fc171eb0db4882c7d9af73ce439ad
- name: coffee_machine/inventory
  newName: coffee_machine/inventory
- name: coffee_machine/order
  newName: coffee_machine/order
